/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_TLS_CLIENT_T_H
#define EDGER8R_TLS_CLIENT_T_H

#include <openenclave/enclave.h>
#include "tls_client_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

int launch_tls_client(char* server_name,
        char* server_port);

OE_EXTERNC_END

#endif // EDGER8R_TLS_CLIENT_T_H
