/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_TLS_SERVER_T_H
#define EDGER8R_TLS_SERVER_T_H

#include <openenclave/enclave.h>
#include "tls_server_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

int setup_tls_server(char* port);

OE_EXTERNC_END

#endif // EDGER8R_TLS_SERVER_T_H
