/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef TLS_SERVER_ARGS_H
#define TLS_SERVER_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

typedef struct _setup_tls_server_args_t {
	int _retval;
	char* port;
	size_t port_len;
    oe_result_t _result;
 } setup_tls_server_args_t;

/* trusted function ids */
enum {
    fcn_id_setup_tls_server = 0,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // TLS_SERVER_ARGS_H
